[package]
name = "battlebots-rs"
version = "0.1.0"
authors = ["cobular <22972550+Cobular@users.noreply.github.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
esp-idf-sys = { version = "0.32", features = ["binstart"] }
esp-idf-hal = "0.40"
embedded-hal = "0.2.7"
embedded-svc = "0.24"
esp-idf-svc = "0.45"
httparse = { version = "1.8.0", default-features = false }
embedded-websocket = "0.8.0"

[build-dependencies]
embuild = "0.30.4"
